LANDMARK_PATH = "models/shape_predictor_68_face_landmarks.dat"

CAMERA_INDEX = 0
FACE_CONFIDENCE_THRESHOLD = 45
EAR_THRESHOLD = 0.23
DROWSY_FRAMES = 25


BREVO_API_KEY = "YOUR_BREVO_API_KEY"


BREVO_SENDER_EMAIL = "cdms.project.ai@gmail.com"

BREVO_SENDER_NAME = "CDMS Security"